import { NextResponse } from "next/server"
import { getSupabaseServerClient } from "@/lib/supabase"

// 50 more cards with various anime characters
const extendedCards = [
  // Dragon Ball Characters
  {
    name: "Super Saiyan",
    character: "Goku",
    image_url: "/goku-super-saiyan.png",
    rarity: "legendary",
    type: "fire",
    hp: 120,
    attack: 115,
    defense: 100,
    speed: 110,
    special_attack: 120,
    special_defense: 100,
    description: "The legendary Super Saiyan with incredible power.",
    active_ability: {
      name: "Kamehameha",
      description: "Fires a powerful energy beam",
      damage: 60,
      cooldown: 3,
    },
    passive_ability: {
      name: "Saiyan Strength",
      description: "Gets stronger after taking damage",
      effect: "berserk",
    },
  },
  {
    name: "Prince of Saiyans",
    character: "Vegeta",
    image_url: "/vegeta-prince.png",
    rarity: "ultra-rare",
    type: "fire",
    hp: 110,
    attack: 120,
    defense: 105,
    speed: 105,
    special_attack: 115,
    special_defense: 95,
    description: "The proud prince of the Saiyan race.",
    active_ability: {
      name: "Final Flash",
      description: "Unleashes a devastating energy blast",
      damage: 55,
      cooldown: 3,
    },
    passive_ability: {
      name: "Saiyan Pride",
      description: "Increases attack when HP is low",
      effect: "berserk",
    },
  },
  {
    name: "Android",
    character: "Android 18",
    image_url: "/android-18.png",
    rarity: "rare",
    type: "lightning",
    hp: 95,
    attack: 90,
    defense: 100,
    speed: 95,
    special_attack: 85,
    special_defense: 90,
    description: "A powerful android with infinite energy.",
    active_ability: {
      name: "Energy Absorption",
      description: "Absorbs enemy energy attacks",
      damage: 30,
      effect: "reflect",
      cooldown: 2,
    },
    passive_ability: {
      name: "Infinite Energy",
      description: "Never tires in battle",
      effect: "endurance",
    },
  },
  {
    name: "Namekian Warrior",
    character: "Piccolo",
    image_url: "/piccolo-warrior.png",
    rarity: "rare",
    type: "earth",
    hp: 100,
    attack: 85,
    defense: 110,
    speed: 90,
    special_attack: 95,
    special_defense: 105,
    description: "A wise Namekian warrior and mentor.",
    active_ability: {
      name: "Special Beam Cannon",
      description: "Fires a piercing energy beam",
      damage: 45,
      effect: "defense_down",
      cooldown: 3,
    },
    passive_ability: {
      name: "Regeneration",
      description: "Slowly regenerates health",
      healing: 10,
      effect: "heal_over_time",
    },
  },
  {
    name: "God of Destruction",
    character: "Beerus",
    image_url: "/beerus-god.png",
    rarity: "legendary",
    type: "chakra",
    hp: 130,
    attack: 125,
    defense: 115,
    speed: 120,
    special_attack: 130,
    special_defense: 120,
    description: "The fearsome God of Destruction.",
    active_ability: {
      name: "Hakai",
      description: "Erases the target from existence",
      damage: 70,
      cooldown: 4,
    },
    passive_ability: {
      name: "God Ki",
      description: "Immune to most status effects",
      effect: "immunity",
    },
  },

  // One Piece Characters
  {
    name: "Straw Hat Captain",
    character: "Luffy",
    image_url: "/luffy-captain.png",
    rarity: "ultra-rare",
    type: "wind",
    hp: 110,
    attack: 105,
    defense: 90,
    speed: 100,
    special_attack: 100,
    special_defense: 95,
    description: "The rubber captain of the Straw Hat Pirates.",
    active_ability: {
      name: "Gum-Gum Gatling",
      description: "Unleashes a flurry of rapid punches",
      damage: 45,
      effect: "area_damage",
      cooldown: 2,
    },
    passive_ability: {
      name: "Rubber Body",
      description: "Resistant to physical attacks",
      effect: "damage_reduction",
    },
  },
  {
    name: "Pirate Hunter",
    character: "Zoro",
    image_url: "/zoro-hunter.png",
    rarity: "ultra-rare",
    type: "wind",
    hp: 105,
    attack: 115,
    defense: 95,
    speed: 95,
    special_attack: 90,
    special_defense: 90,
    description: "The three-sword style swordsman of the Straw Hat Pirates.",
    active_ability: {
      name: "Three Sword Style: Oni Giri",
      description: "A powerful three-sword slash",
      damage: 50,
      effect: "critical",
      cooldown: 2,
    },
    passive_ability: {
      name: "Bushido Spirit",
      description: "Chance to counter attacks",
      effect: "counter",
    },
  },
  {
    name: "Cat Burglar",
    character: "Nami",
    image_url: "/nami-burglar.png",
    rarity: "rare",
    type: "lightning",
    hp: 85,
    attack: 75,
    defense: 80,
    speed: 95,
    special_attack: 100,
    special_defense: 85,
    description: "The navigator of the Straw Hat Pirates.",
    active_ability: {
      name: "Thunderbolt Tempo",
      description: "Summons a powerful lightning strike",
      damage: 40,
      effect: "stun",
      cooldown: 3,
    },
    passive_ability: {
      name: "Weather Prediction",
      description: "Can predict and avoid some attacks",
      effect: "dodge",
    },
  },
  {
    name: "Surgeon of Death",
    character: "Trafalgar Law",
    image_url: "/law-surgeon.png",
    rarity: "ultra-rare",
    type: "chakra",
    hp: 95,
    attack: 90,
    defense: 85,
    speed: 100,
    special_attack: 110,
    special_defense: 90,
    description: "A powerful pirate with the Op-Op Fruit ability.",
    active_ability: {
      name: "Room: Shambles",
      description: "Creates a space where he can manipulate anything",
      effect: "control",
      cooldown: 3,
    },
    passive_ability: {
      name: "Surgeon's Precision",
      description: "Increased critical hit chance",
      effect: "critical",
    },
  },
  {
    name: "Emperor",
    character: "Shanks",
    image_url: "/shanks-emperor.png",
    rarity: "legendary",
    type: "fire",
    hp: 120,
    attack: 125,
    defense: 110,
    speed: 115,
    special_attack: 120,
    special_defense: 115,
    description: "One of the Four Emperors of the sea.",
    active_ability: {
      name: "Conqueror's Haki",
      description: "Overwhelms opponents with willpower",
      effect: "stun",
      cooldown: 4,
    },
    passive_ability: {
      name: "Emperor's Presence",
      description: "Intimidates enemies, lowering their attack",
      effect: "attack_down",
    },
  },

  // My Hero Academia Characters
  {
    name: "Hero in Training",
    character: "Deku",
    image_url: "/deku-training.png",
    rarity: "rare",
    type: "earth",
    hp: 90,
    attack: 95,
    defense: 85,
    speed: 90,
    special_attack: 100,
    special_defense: 85,
    description: "A determined hero with the power of One For All.",
    active_ability: {
      name: "Detroit Smash",
      description: "A powerful punch at 100% power",
      damage: 45,
      effect: "self_damage",
      cooldown: 2,
    },
    passive_ability: {
      name: "One For All",
      description: "Increases all stats as the battle progresses",
      effect: "stat_boost",
    },
  },
  {
    name: "Explosion King",
    character: "Bakugo",
    image_url: "/bakugo-explosion.png",
    rarity: "rare",
    type: "fire",
    hp: 85,
    attack: 105,
    defense: 80,
    speed: 95,
    special_attack: 110,
    special_defense: 75,
    description: "A fierce hero with explosive abilities.",
    active_ability: {
      name: "Howitzer Impact",
      description: "A devastating explosive attack",
      damage: 50,
      effect: "area_damage",
      cooldown: 3,
    },
    passive_ability: {
      name: "Explosive Temper",
      description: "Attack increases when taking damage",
      effect: "berserk",
    },
  },
  {
    name: "Ice and Fire",
    character: "Todoroki",
    image_url: "/todoroki-dual.png",
    rarity: "ultra-rare",
    type: "water",
    hp: 95,
    attack: 90,
    defense: 100,
    speed: 85,
    special_attack: 115,
    special_defense: 105,
    description: "A powerful hero with both ice and fire powers.",
    active_ability: {
      name: "Heaven-Piercing Ice Wall",
      description: "Creates a massive ice barrier",
      damage: 40,
      effect: "defense_up",
      cooldown: 2,
    },
    passive_ability: {
      name: "Half-Cold Half-Hot",
      description: "Can switch between fire and ice attacks",
      effect: "versatility",
    },
  },
  {
    name: "Symbol of Peace",
    character: "All Might",
    image_url: "/all-might-symbol.png",
    rarity: "legendary",
    type: "earth",
    hp: 125,
    attack: 130,
    defense: 120,
    speed: 115,
    special_attack: 125,
    special_defense: 115,
    description: "The number one hero and Symbol of Peace.",
    active_ability: {
      name: "United States of Smash",
      description: "The ultimate smash attack",
      damage: 65,
      cooldown: 4,
    },
    passive_ability: {
      name: "Plus Ultra",
      description: "Boosts all allies' stats",
      effect: "team_boost",
    },
  },
  {
    name: "Hero Killer",
    character: "Stain",
    image_url: "/stain-killer.png",
    rarity: "ultra-rare",
    type: "fire",
    hp: 90,
    attack: 110,
    defense: 85,
    speed: 105,
    special_attack: 95,
    special_defense: 80,
    description: "A dangerous villain who targets heroes.",
    active_ability: {
      name: "Bloodcurdle",
      description: "Paralyzes opponents by ingesting their blood",
      effect: "immobilize",
      cooldown: 3,
    },
    passive_ability: {
      name: "Conviction",
      description: "Increases attack against stronger opponents",
      effect: "underdog",
    },
  },

  // Demon Slayer Characters
  {
    name: "Water Hashira",
    character: "Giyu Tomioka",
    image_url: "/giyu-water.png",
    rarity: "ultra-rare",
    type: "water",
    hp: 100,
    attack: 105,
    defense: 100,
    speed: 110,
    special_attack: 105,
    special_defense: 100,
    description: "The stoic Water Hashira of the Demon Slayer Corps.",
    active_ability: {
      name: "Eleventh Form: Dead Calm",
      description: "A defensive technique that nullifies attacks",
      effect: "counter",
      cooldown: 3,
    },
    passive_ability: {
      name: "Water Breathing",
      description: "Flowing movements that increase evasion",
      effect: "dodge",
    },
  },
  {
    name: "Flame Hashira",
    character: "Kyojuro Rengoku",
    image_url: "/rengoku-flame.png",
    rarity: "ultra-rare",
    type: "fire",
    hp: 105,
    attack: 115,
    defense: 95,
    speed: 105,
    special_attack: 110,
    special_defense: 95,
    description: "The passionate Flame Hashira of the Demon Slayer Corps.",
    active_ability: {
      name: "Ninth Form: Rengoku",
      description: "A powerful flaming slash",
      damage: 55,
      cooldown: 3,
    },
    passive_ability: {
      name: "Flame Breathing",
      description: "Increases attack with each consecutive hit",
      effect: "momentum",
    },
  },
  {
    name: "Demon Slayer",
    character: "Tanjiro Kamado",
    image_url: "/tanjiro-slayer.png",
    rarity: "rare",
    type: "water",
    hp: 95,
    attack: 90,
    defense: 85,
    speed: 95,
    special_attack: 95,
    special_defense: 90,
    description: "A determined demon slayer with a strong sense of smell.",
    active_ability: {
      name: "Hinokami Kagura: Sun Halo Dragon Dance",
      description: "A powerful fire-based sword technique",
      damage: 45,
      cooldown: 2,
    },
    passive_ability: {
      name: "Heightened Senses",
      description: "Can detect enemy weaknesses",
      effect: "accuracy_up",
    },
  },
  {
    name: "Thunder Hashira",
    character: "Zenitsu Agatsuma",
    image_url: "/zenitsu-thunder.png",
    rarity: "rare",
    type: "lightning",
    hp: 85,
    attack: 100,
    defense: 75,
    speed: 120,
    special_attack: 105,
    special_defense: 80,
    description: "A cowardly demon slayer who unleashes his true power when unconscious.",
    active_ability: {
      name: "First Form: Thunderclap and Flash",
      description: "An incredibly fast sword strike",
      damage: 40,
      effect: "speed_up",
      cooldown: 2,
    },
    passive_ability: {
      name: "Unconscious Fighting",
      description: "Becomes stronger when HP is low",
      effect: "berserk",
    },
  },
  {
    name: "Upper Moon One",
    character: "Kokushibo",
    image_url: "/kokushibo-moon.png",
    rarity: "legendary",
    type: "wind",
    hp: 125,
    attack: 130,
    defense: 115,
    speed: 120,
    special_attack: 125,
    special_defense: 115,
    description: "The strongest of the Twelve Kizuki demons.",
    active_ability: {
      name: "Moon Breathing: First Form",
      description: "A devastating attack with multiple slashes",
      damage: 65,
      effect: "area_damage",
      cooldown: 4,
    },
    passive_ability: {
      name: "Demon Regeneration",
      description: "Rapidly regenerates health",
      healing: 15,
      effect: "heal_over_time",
    },
  },

  // Attack on Titan Characters
  {
    name: "Attack Titan",
    character: "Eren Yeager",
    image_url: "/eren-titan.png",
    rarity: "ultra-rare",
    type: "earth",
    hp: 115,
    attack: 110,
    defense: 105,
    speed: 90,
    special_attack: 100,
    special_defense: 95,
    description: "A determined soldier with the power to transform into a Titan.",
    active_ability: {
      name: "Titan Transformation",
      description: "Transforms into the Attack Titan",
      damage: 50,
      effect: "stat_boost",
      cooldown: 3,
    },
    passive_ability: {
      name: "Regeneration",
      description: "Slowly regenerates health",
      healing: 10,
      effect: "heal_over_time",
    },
  },
  {
    name: "Humanity's Strongest",
    character: "Levi Ackerman",
    image_url: "/levi-strongest.png",
    rarity: "legendary",
    type: "wind",
    hp: 100,
    attack: 125,
    defense: 95,
    speed: 130,
    special_attack: 115,
    special_defense: 90,
    description: "The strongest soldier in the Survey Corps.",
    active_ability: {
      name: "Spinning Attack",
      description: "A devastating spinning blade attack",
      damage: 60,
      effect: "area_damage",
      cooldown: 3,
    },
    passive_ability: {
      name: "Ackerman Blood",
      description: "Increased combat abilities",
      effect: "stat_boost",
    },
  },
  {
    name: "Female Titan",
    character: "Annie Leonhart",
    image_url: "/annie-titan.png",
    rarity: "ultra-rare",
    type: "earth",
    hp: 110,
    attack: 105,
    defense: 110,
    speed: 100,
    special_attack: 95,
    special_defense: 100,
    description: "A skilled fighter who can transform into the Female Titan.",
    active_ability: {
      name: "Crystallization",
      description: "Hardens body parts for defense and attack",
      effect: "defense_up",
      cooldown: 2,
    },
    passive_ability: {
      name: "Martial Arts Mastery",
      description: "Skilled in hand-to-hand combat",
      effect: "counter",
    },
  },
  {
    name: "Colossal Titan",
    character: "Armin Arlert",
    image_url: "/armin-titan.png",
    rarity: "ultra-rare",
    type: "fire",
    hp: 130,
    attack: 100,
    defense: 120,
    speed: 70,
    special_attack: 115,
    special_defense: 105,
    description: "A strategic genius who inherited the power of the Colossal Titan.",
    active_ability: {
      name: "Steam Release",
      description: "Releases scalding steam in all directions",
      damage: 40,
      effect: "area_damage",
      cooldown: 3,
    },
    passive_ability: {
      name: "Strategic Mind",
      description: "Increases team's defense",
      effect: "team_defense_up",
    },
  },
  {
    name: "Beast Titan",
    character: "Zeke Yeager",
    image_url: "/zeke-titan.png",
    rarity: "ultra-rare",
    type: "earth",
    hp: 115,
    attack: 105,
    defense: 110,
    speed: 85,
    special_attack: 110,
    special_defense: 100,
    description: "A calculating warrior who can transform into the Beast Titan.",
    active_ability: {
      name: "Projectile Barrage",
      description: "Throws a barrage of hardened projectiles",
      damage: 45,
      effect: "area_damage",
      cooldown: 3,
    },
    passive_ability: {
      name: "Royal Blood",
      description: "Enhanced Titan abilities",
      effect: "stat_boost",
    },
  },

  // Jujutsu Kaisen Characters
  {
    name: "Limitless User",
    character: "Satoru Gojo",
    image_url: "/gojo-limitless.png",
    rarity: "legendary",
    type: "chakra",
    hp: 120,
    attack: 120,
    defense: 125,
    speed: 125,
    special_attack: 130,
    special_defense: 125,
    description: "The strongest jujutsu sorcerer with the Limitless technique.",
    active_ability: {
      name: "Hollow Purple",
      description: "Combines positive and negative energy for a devastating attack",
      damage: 70,
      cooldown: 4,
    },
    passive_ability: {
      name: "Infinity",
      description: "Automatically reduces damage taken",
      effect: "damage_reduction",
    },
  },
  {
    name: "Sukuna Vessel",
    character: "Yuji Itadori",
    image_url: "/yuji-vessel.png",
    rarity: "ultra-rare",
    type: "earth",
    hp: 105,
    attack: 110,
    defense: 95,
    speed: 105,
    special_attack: 100,
    special_defense: 90,
    description: "A physically gifted student who became the vessel for Sukuna.",
    active_ability: {
      name: "Black Flash",
      description: "A perfect application of cursed energy",
      damage: 50,
      effect: "critical",
      cooldown: 2,
    },
    passive_ability: {
      name: "Superhuman Strength",
      description: "Naturally enhanced physical abilities",
      effect: "stat_boost",
    },
  },
  {
    name: "Ten Shadows User",
    character: "Megumi Fushiguro",
    image_url: "/megumi-shadows.png",
    rarity: "rare",
    type: "chakra",
    hp: 90,
    attack: 85,
    defense: 90,
    speed: 95,
    special_attack: 105,
    special_defense: 95,
    description: "A serious sorcerer with the Ten Shadows technique.",
    active_ability: {
      name: "Divine Dogs",
      description: "Summons shadow dogs to attack",
      damage: 35,
      effect: "summon",
      cooldown: 2,
    },
    passive_ability: {
      name: "Shadow Manipulation",
      description: "Can hide in shadows to avoid attacks",
      effect: "dodge",
    },
  },
  {
    name: "Cursed Speech",
    character: "Toge Inumaki",
    image_url: "/toge-speech.png",
    rarity: "rare",
    type: "wind",
    hp: 85,
    attack: 80,
    defense: 85,
    speed: 90,
    special_attack: 100,
    special_defense: 90,
    description: "A sorcerer whose words have cursed power.",
    active_ability: {
      name: "Don't Move",
      description: "Forces the target to stop moving",
      effect: "immobilize",
      cooldown: 3,
    },
    passive_ability: {
      name: "Cursed Speech",
      description: "Words carry power that can affect reality",
      effect: "control",
    },
  },
  {
    name: "King of Curses",
    character: "Ryomen Sukuna",
    image_url: "/sukuna-king.png",
    rarity: "legendary",
    type: "fire",
    hp: 130,
    attack: 135,
    defense: 120,
    speed: 125,
    special_attack: 140,
    special_defense: 125,
    description: "The legendary King of Curses.",
    active_ability: {
      name: "Malevolent Shrine",
      description: "Creates a domain where all attacks hit",
      damage: 75,
      effect: "area_damage",
      cooldown: 5,
    },
    passive_ability: {
      name: "Immortality",
      description: "Can revive once per battle",
      effect: "revive",
    },
  },

  // Hunter x Hunter Characters
  {
    name: "Transmuter",
    character: "Killua Zoldyck",
    image_url: "/killua-lightning.png",
    rarity: "ultra-rare",
    type: "lightning",
    hp: 95,
    attack: 105,
    defense: 90,
    speed: 125,
    special_attack: 110,
    special_defense: 95,
    description: "A former assassin with lightning abilities.",
    active_ability: {
      name: "Godspeed",
      description: "Moves at incredible speed to attack",
      damage: 45,
      effect: "speed_up",
      cooldown: 3,
    },
    passive_ability: {
      name: "Assassin Training",
      description: "Increased critical hit chance",
      effect: "critical",
    },
  },
  {
    name: "Enhancer",
    character: "Gon Freecss",
    image_url: "/gon-enhancer.png",
    rarity: "rare",
    type: "earth",
    hp: 100,
    attack: 110,
    defense: 90,
    speed: 100,
    special_attack: 105,
    special_defense: 85,
    description: "A determined Hunter with incredible potential.",
    active_ability: {
      name: "Jajanken: Rock",
      description: "A powerful focused punch",
      damage: 50,
      cooldown: 2,
    },
    passive_ability: {
      name: "Determination",
      description: "Gets stronger as the battle progresses",
      effect: "stat_boost",
    },
  },
  {
    name: "Chain User",
    character: "Kurapika",
    image_url: "/kurapika-chain.png",
    rarity: "rare",
    type: "chakra",
    hp: 90,
    attack: 95,
    defense: 95,
    speed: 100,
    special_attack: 100,
    special_defense: 100,
    description: "A Hunter seeking vengeance for his clan.",
    active_ability: {
      name: "Chain Jail",
      description: "Binds the target with unbreakable chains",
      effect: "immobilize",
      cooldown: 3,
    },
    passive_ability: {
      name: "Scarlet Eyes",
      description: "Eyes turn scarlet when angry, increasing all abilities",
      effect: "berserk",
    },
  },
  {
    name: "Magician",
    character: "Hisoka",
    image_url: "/hisoka-magician.png",
    rarity: "ultra-rare",
    type: "chakra",
    hp: 100,
    attack: 115,
    defense: 95,
    speed: 110,
    special_attack: 105,
    special_defense: 90,
    description: "A dangerous and unpredictable fighter.",
    active_ability: {
      name: "Bungee Gum",
      description: "Has the properties of both rubber and gum",
      effect: "control",
      cooldown: 2,
    },
    passive_ability: {
      name: "Bloodlust",
      description: "Gets stronger when fighting powerful opponents",
      effect: "underdog",
    },
  },
  {
    name: "Chairman",
    character: "Isaac Netero",
    image_url: "/netero-chairman.png",
    rarity: "legendary",
    type: "chakra",
    hp: 115,
    attack: 130,
    defense: 120,
    speed: 125,
    special_attack: 135,
    special_defense: 120,
    description: "The legendary chairman of the Hunter Association.",
    active_ability: {
      name: "100-Type Guanyin Bodhisattva",
      description: "Summons a giant statue for devastating attacks",
      damage: 65,
      effect: "area_damage",
      cooldown: 4,
    },
    passive_ability: {
      name: "Meditation",
      description: "Increases attack and defense each turn",
      effect: "stat_boost",
    },
  },

  // Fullmetal Alchemist Characters
  {
    name: "Fullmetal Alchemist",
    character: "Edward Elric",
    image_url: "/edward-alchemist.png",
    rarity: "ultra-rare",
    type: "earth",
    hp: 95,
    attack: 100,
    defense: 95,
    speed: 100,
    special_attack: 110,
    special_defense: 95,
    description: "A skilled alchemist with an automail arm and leg.",
    active_ability: {
      name: "Transmutation",
      description: "Reshapes the environment into weapons",
      damage: 45,
      effect: "versatility",
      cooldown: 2,
    },
    passive_ability: {
      name: "Automail Limbs",
      description: "Increased durability and strength",
      effect: "endurance",
    },
  },
  {
    name: "Armored Alchemist",
    character: "Alphonse Elric",
    image_url: "/alphonse-armor.png",
    rarity: "rare",
    type: "earth",
    hp: 120,
    attack: 90,
    defense: 120,
    speed: 85,
    special_attack: 95,
    special_defense: 110,
    description: "A soul bound to a suit of armor.",
    active_ability: {
      name: "Armored Assault",
      description: "Uses his armored body for powerful attacks",
      damage: 40,
      effect: "defense_up",
      cooldown: 2,
    },
    passive_ability: {
      name: "Hollow Armor",
      description: "Immune to poison and status effects",
      effect: "immunity",
    },
  },
  {
    name: "Flame Alchemist",
    character: "Roy Mustang",
    image_url: "/mustang-flame.png",
    rarity: "ultra-rare",
    type: "fire",
    hp: 90,
    attack: 105,
    defense: 85,
    speed: 95,
    special_attack: 120,
    special_defense: 90,
    description: "A military officer who can create and control fire.",
    active_ability: {
      name: "Flame Alchemy",
      description: "Creates precise, devastating flames",
      damage: 55,
      effect: "area_damage",
      cooldown: 3,
    },
    passive_ability: {
      name: "Strategic Mind",
      description: "Increases team's attack",
      effect: "team_attack_up",
    },
  },
  {
    name: "Homunculus",
    character: "Greed",
    image_url: "/greed-homunculus.png",
    rarity: "rare",
    type: "earth",
    hp: 110,
    attack: 100,
    defense: 115,
    speed: 90,
    special_attack: 85,
    special_defense: 95,
    description: "A homunculus with the Ultimate Shield ability.",
    active_ability: {
      name: "Ultimate Shield",
      description: "Hardens skin to become nearly impenetrable",
      effect: "defense_up",
      cooldown: 2,
    },
    passive_ability: {
      name: "Regeneration",
      description: "Slowly regenerates health",
      healing: 10,
      effect: "heal_over_time",
    },
  },
  {
    name: "Father",
    character: "Homunculus Father",
    image_url: "/father-homunculus.png",
    rarity: "legendary",
    type: "chakra",
    hp: 125,
    attack: 120,
    defense: 125,
    speed: 110,
    special_attack: 130,
    special_defense: 125,
    description: "The original homunculus and creator of the others.",
    active_ability: {
      name: "Philosopher's Stone",
      description: "Uses the power of countless souls",
      damage: 65,
      effect: "area_damage",
      cooldown: 4,
    },
    passive_ability: {
      name: "All Alchemy",
      description: "Can use any alchemical ability",
      effect: "versatility",
    },
  },
]

export async function GET() {
  try {
    const supabase = getSupabaseServerClient()

    // Insert cards
    const { data, error } = await supabase.from("cards").insert(extendedCards).select()

    if (error) {
      console.error("Error seeding extended cards:", error)
      return NextResponse.json({ error: error.message }, { status: 500 })
    }

    return NextResponse.json({ success: true, count: data.length })
  } catch (error) {
    console.error("Error in seed-extended-cards route:", error)
    return NextResponse.json({ error: "Internal server error" }, { status: 500 })
  }
}
