import { NextResponse } from "next/server"
import { getSupabaseServerClient } from "@/lib/supabase"

// More cards with different versions of the same characters
const moreCards = [
  // Naruto variants
  {
    name: "Academy Student",
    character: "Naruto Uzumaki",
    image_url: "/naruto-academy.png",
    rarity: "common",
    type: "wind",
    hp: 60,
    attack: 50,
    defense: 45,
    speed: 65,
    special_attack: 55,
    special_defense: 40,
    description: "Young Naruto during his days at the Ninja Academy.",
    active_ability: {
      name: "Mischief",
      description: "Plays a prank that confuses the opponent",
      damage: 10,
      cooldown: 1,
    },
    passive_ability: {
      name: "Determination",
      description: "Never gives up, gaining strength when HP is low",
      effect: "endurance",
    },
  },
  {
    name: "Genin Ninja",
    character: "Naruto Uzumaki",
    image_url: "/naruto-genin.png",
    rarity: "uncommon",
    type: "wind",
    hp: 70,
    attack: 65,
    defense: 55,
    speed: 70,
    special_attack: 70,
    special_defense: 60,
    description: "Naruto as a newly graduated Genin of the Hidden Leaf Village.",
    active_ability: {
      name: "Shadow Clone",
      description: "Creates clones to attack the opponent",
      damage: 20,
      cooldown: 2,
    },
    passive_ability: {
      name: "Nine-Tails Chakra",
      description: "Occasionally taps into the Nine-Tails power",
      healing: 5,
      effect: "minor_heal",
    },
  },
  {
    name: "Sage Mode Master",
    character: "Naruto Uzumaki",
    image_url: "/naruto-sage.png",
    rarity: "ultra-rare",
    type: "wind",
    hp: 100,
    attack: 95,
    defense: 85,
    speed: 90,
    special_attack: 100,
    special_defense: 90,
    description: "Naruto after mastering the Sage Mode technique.",
    active_ability: {
      name: "Rasenshuriken",
      description: "Throws a powerful wind-style Rasengan",
      damage: 45,
      cooldown: 3,
    },
    passive_ability: {
      name: "Nature Energy",
      description: "Absorbs nature energy to enhance abilities",
      effect: "stat_boost",
    },
  },
  {
    name: "Six Paths Sage",
    character: "Naruto Uzumaki",
    image_url: "/naruto-six-paths.png",
    rarity: "legendary",
    type: "chakra",
    hp: 120,
    attack: 110,
    defense: 100,
    speed: 100,
    special_attack: 120,
    special_defense: 110,
    description: "Naruto with the power of the Six Paths Sage Mode.",
    active_ability: {
      name: "Six Paths: Massive Rasengan",
      description: "Creates an enormous Rasengan with Six Paths power",
      damage: 60,
      cooldown: 4,
    },
    passive_ability: {
      name: "Truth-Seeking Orbs",
      description: "Orbs that negate all ninjutsu",
      effect: "team_boost",
    },
  },

  // Sasuke variants
  {
    name: "Academy Prodigy",
    character: "Sasuke Uchiha",
    image_url: "/sasuke-academy.png",
    rarity: "uncommon",
    type: "fire",
    hp: 65,
    attack: 70,
    defense: 60,
    speed: 75,
    special_attack: 65,
    special_defense: 60,
    description: "Young Sasuke, top of his class at the Ninja Academy.",
    active_ability: {
      name: "Fireball Jutsu",
      description: "Breathes a medium-sized fireball",
      damage: 25,
      cooldown: 2,
    },
    passive_ability: {
      name: "Uchiha Blood",
      description: "Natural talent for combat",
      effect: "accuracy_up",
    },
  },
  {
    name: "Curse Mark Bearer",
    character: "Sasuke Uchiha",
    image_url: "/sasuke-curse-mark.png",
    rarity: "rare",
    type: "fire",
    hp: 80,
    attack: 85,
    defense: 75,
    speed: 85,
    special_attack: 90,
    special_defense: 75,
    description: "Sasuke after receiving Orochimaru's Curse Mark.",
    active_ability: {
      name: "Chidori",
      description: "Charges lightning in hand for a piercing attack",
      damage: 35,
      effect: "critical",
      cooldown: 2,
    },
    passive_ability: {
      name: "Curse Mark Release",
      description: "Activates the curse mark when in danger",
      effect: "berserk",
    },
  },
  {
    name: "Mangekyo Wielder",
    character: "Sasuke Uchiha",
    image_url: "/sasuke-mangekyo.png",
    rarity: "ultra-rare",
    type: "fire",
    hp: 95,
    attack: 100,
    defense: 90,
    speed: 95,
    special_attack: 105,
    special_defense: 90,
    description: "Sasuke after awakening the Mangekyo Sharingan.",
    active_ability: {
      name: "Amaterasu",
      description: "Summons black flames that cannot be extinguished",
      damage: 45,
      effect: "area_damage",
      cooldown: 3,
    },
    passive_ability: {
      name: "Susanoo",
      description: "Manifests a spectral warrior for protection",
      effect: "damage_reduction",
    },
  },
  {
    name: "Eternal Rinnegan",
    character: "Sasuke Uchiha",
    image_url: "/sasuke-rinnegan.png",
    rarity: "legendary",
    type: "lightning",
    hp: 115,
    attack: 115,
    defense: 105,
    speed: 110,
    special_attack: 120,
    special_defense: 100,
    description: "Sasuke with the Eternal Mangekyo Sharingan and Rinnegan.",
    active_ability: {
      name: "Indra's Arrow",
      description: "Launches a powerful lightning arrow",
      damage: 60,
      effect: "stun",
      cooldown: 4,
    },
    passive_ability: {
      name: "Space-Time Manipulation",
      description: "Can swap places with objects or people",
      effect: "dodge",
    },
  },

  // Sakura variants
  {
    name: "Academy Student",
    character: "Sakura Haruno",
    image_url: "/sakura-academy.png",
    rarity: "common",
    type: "earth",
    hp: 55,
    attack: 40,
    defense: 50,
    speed: 60,
    special_attack: 45,
    special_defense: 65,
    description: "Young Sakura during her Academy days.",
    active_ability: {
      name: "Basic Medical Jutsu",
      description: "Heals minor wounds",
      healing: 15,
      cooldown: 2,
    },
    passive_ability: {
      name: "Book Smarts",
      description: "Knowledge of ninja techniques",
      effect: "minor_heal",
    },
  },
  {
    name: "Medical Ninja Apprentice",
    character: "Sakura Haruno",
    image_url: "/sakura-apprentice.png",
    rarity: "rare",
    type: "earth",
    hp: 75,
    attack: 70,
    defense: 75,
    speed: 80,
    special_attack: 85,
    special_defense: 90,
    description: "Sakura as Tsunade's apprentice, learning medical ninjutsu.",
    active_ability: {
      name: "Chakra Enhanced Strength",
      description: "Concentrates chakra for a powerful punch",
      damage: 30,
      effect: "defense_down",
      cooldown: 2,
    },
    passive_ability: {
      name: "Medical Knowledge",
      description: "Can heal allies during battle",
      healing: 20,
      effect: "team_heal",
    },
  },
  {
    name: "War Medic",
    character: "Sakura Haruno",
    image_url: "/sakura-war.png",
    rarity: "ultra-rare",
    type: "earth",
    hp: 90,
    attack: 95,
    defense: 85,
    speed: 90,
    special_attack: 100,
    special_defense: 105,
    description: "Sakura during the Fourth Great Ninja War.",
    active_ability: {
      name: "Hundred Healings Jutsu",
      description: "Releases stored chakra for immense healing",
      healing: 40,
      cooldown: 3,
    },
    passive_ability: {
      name: "Mitotic Regeneration",
      description: "Rapidly heals from injuries",
      effect: "heal_over_time",
    },
  },

  // Kakashi variants
  {
    name: "Young Jonin",
    character: "Kakashi Hatake",
    image_url: "/kakashi-young.png",
    rarity: "rare",
    type: "lightning",
    hp: 80,
    attack: 85,
    defense: 80,
    speed: 90,
    special_attack: 85,
    special_defense: 80,
    description: "Kakashi as a young Jonin, before Team 7.",
    active_ability: {
      name: "White Light Chakra Sabre",
      description: "Attacks with his father's white chakra blade",
      damage: 30,
      effect: "critical",
      cooldown: 2,
    },
    passive_ability: {
      name: "Genius Intellect",
      description: "Analyzes enemy techniques",
      effect: "accuracy_up",
    },
  },
  {
    name: "ANBU Captain",
    character: "Kakashi Hatake",
    image_url: "/kakashi-anbu.png",
    rarity: "ultra-rare",
    type: "lightning",
    hp: 90,
    attack: 95,
    defense: 90,
    speed: 100,
    special_attack: 95,
    special_defense: 90,
    description: "Kakashi during his time as an ANBU Black Ops captain.",
    active_ability: {
      name: "Assassin's Strike",
      description: "Performs a precise, lethal attack",
      damage: 40,
      effect: "critical",
      cooldown: 2,
    },
    passive_ability: {
      name: "Stealth Mastery",
      description: "Chance to evade attacks",
      effect: "dodge",
    },
  },
  {
    name: "Double Sharingan",
    character: "Kakashi Hatake",
    image_url: "/kakashi-double-sharingan.png",
    rarity: "legendary",
    type: "lightning",
    hp: 100,
    attack: 105,
    defense: 95,
    speed: 105,
    special_attack: 110,
    special_defense: 100,
    description: "Kakashi with both Sharingan eyes during the Fourth Great Ninja War.",
    active_ability: {
      name: "Perfect Susanoo",
      description: "Manifests a complete Susanoo",
      damage: 55,
      effect: "area_damage",
      cooldown: 4,
    },
    passive_ability: {
      name: "Kamui",
      description: "Can phase through attacks",
      effect: "dodge",
    },
  },
]

export async function GET() {
  try {
    const supabase = getSupabaseServerClient()

    // Insert cards
    const { data, error } = await supabase.from("cards").insert(moreCards).select()

    if (error) {
      console.error("Error seeding more cards:", error)
      return NextResponse.json({ error: error.message }, { status: 500 })
    }

    return NextResponse.json({ success: true, count: data.length })
  } catch (error) {
    console.error("Error in seed-more-cards route:", error)
    return NextResponse.json({ error: "Internal server error" }, { status: 500 })
  }
}
