-- Restore the deleted "Starter Squad" challenge
INSERT INTO "public"."sbc_challenges" (
  "id", 
  "name", 
  "description", 
  "difficulty", 
  "rewards_tickets", 
  "rewards_elite_tickets", 
  "rewards_icon_tickets", 
  "special_reward", 
  "requirements_total_cards", 
  "requirements_min_level", 
  "requirements_specific_rarities", 
  "is_active", 
  "created_at", 
  "updated_at", 
  "requirements_team_rating", 
  "requirements_rarity_level_counts", 
  "is_repeatable", 
  "start_date", 
  "end_date"
) VALUES (
  '1', 
  'Starter Squad', 
  'Build a balanced team with specific rarity requirements: 7 Basic cards (level 2+), 3 Rare cards (level 1+), 1 Elite card (level 1+), and overall team rating of 77+', 
  'Easy', 
  '5', 
  '3', 
  '0', 
  null, 
  '11', 
  '1', 
  null, 
  'true', 
  '2025-08-04 22:47:22.524337+00', 
  '2025-08-06 19:44:07.57402+00', 
  '77', 
  '{"rare":{"count":3,"min_level":1},"basic":{"count":7,"min_level":2},"elite":{"count":1,"min_level":1}}', 
  'false', 
  '2025-08-08 01:09:37.293079+00', 
  null
);
